Repository CropAi/Backend, pull requests merged in 2020-04, with the labels that each got.

#78 Added appropriate Github actions for the project
  .github/workflows/auto_assign.yml
  .github/workflows/greetings.yml
  .github/workflows/language.yml
  .github/workflows/stale.yml
Labels: PR: unreviewed

#81 Changes made for actions test
  README.md
Labels: PR: reviewed-approved

#83 Made changes to the actions which were failing
  .github/auto_assign.yml
  .github/workflows/stale.yml
  README.md
Labels: PR: unreviewed

#86 Added working screenshot
  .gitignore
  screenshots_folder/abhu-A-J.png
Labels: PR: unreviewed

#88 Added result as json
  data.js
  package-lock.json
  package.json
  public/index.html
  server.js
Labels: PR: unreviewed

#90 add icon to index.html
  public/img/icon.png
  public/index.html
Labels: PR: unreviewed

#94 Data refactor
  data.js
Labels: PR: unreviewed

#96 File successfully uploaded
  screenshots_folder/shreya_screenshot.png
  upload_f912aa30083dcbb63f426647c260fc2e.jpeg
Labels: PR: unreviewed

#97 Backend testing
  screenshots_folder/shreya.png
Labels: PR: unreviewed

#98 Backend running
  screenshots_folder/testing_backendAshish.png
Labels: PR: unreviewed

#93 Added disabling of button feature!
  public/css/style.css
  public/img/loader.gif
  public/index.html
  server.js
Labels: PR: unreviewed

#100 Added script to create folder named test_images
  package.json
  setupDir.sh
  test_images/upload_3ff0e082edf3f88dfc2ab33a226eed47.JPG
  test_images/upload_bf2162ee220c466d0af48500473a4c91.JPG
Labels: PR: unreviewed

#101 Code docs
  README.md
  public/index.html
  server.js
Labels: PR: unreviewed

#103 Delete files from shell script
  .gitignore
  package.json
  server.js
  shell_scripts/deleteDir.sh
  shell_scripts/setupDir.sh
Labels: PR: unreviewed

#104 added working model screen shot
  screenshots_folder/Abhishek_Gupta.PNG
Labels: PR: unreviewed

#105 Replaced shell with fs module
  server.js
  shell_scripts/deleteDir.sh
  shell_scripts/setupDir.sh
Labels: PR: unreviewed

#107 Res timeout
  label_image.py
  server.js
Labels: PR: unreviewed

#110 Backend testing
  screenshots_folder/adyasha8105.jpeg
Labels: PR: partially-approved, gssoc20, hard

#109 Btn fix: disappearing on no file
  public/index.html
Labels: PR: unreviewed

#112 Addition of cors package as global middleware
  package-lock.json
  package.json
  server.js
Labels: PR: unreviewed

#113 Tested Backend
  screenshots_folder/Dibakar-BackendTest.png
Labels: PR: unreviewed

#115 api testing screenshot
  api_testing/Sapna.png
Labels: PR: unreviewed

#116 api_testing screenshot added
  api_testing/shweta_Gurnani.png
Labels: PR: unreviewed

#117 postman api test screenshot added
  api_testing/abhu-A-J.png
Labels: PR: unreviewed

#118 Screenshot_api_testing added
  api_testing/Satyam_Chaudhary.png
Labels: PR: unreviewed

#120 postman result
  api_testing/shreya-api.png
Labels: PR: unreviewed

#121 API testing
  api_testing/Adyasha.jpg
Labels: PR: unreviewed

#122 backend testing
  screenshots_folder/satyam_backend.png
Labels: PR: unreviewed

#124 Api testing
  api_testing/Geesa.jpg
Labels: PR: unreviewed

#125 postman API testing
  api_testing/postman_test_Ashish.png
Labels: PR: unreviewed

#127 Monkey Patching
  server.js
Labels: PR: unreviewed

#128 Backend testing
  screenshots_folder/Geesa-Backend.PNG
Labels: PR: unreviewed

#129 Backend_testing screenshot added
  screenshots_folder/shweta_gurnani.png
Labels: PR: unreviewed

#130 added screen shot
  api_testing/api_testing_abhishek_gupta.PNG
Labels: PR: unreviewed

#131 Backend Testing screenshot added
  screenshots_folder/Kuljeet-backend.png
Labels: PR: unreviewed

#133 Create LICENSE
  LICENSE
Labels: PR: unreviewed

#135 Implementation of load balancers using clusters
  app.js
  package.json
  server.js
Labels: PR: unreviewed

#136 added screenshot for api testing in postman
  api_testing/Sk_Shahnawaz.png
Labels: PR: unreviewed

#141 License added
  LICENSE
Labels: PR: unreviewed
